services:
# Servicios de base de datos
  postgres-productos:
    image: postgres:15-alpine #Version de Postgres ligera
    container_name: postgres-productos
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: productos_user
      POSTGRES_PASSWORD: productos_pass
    ports:
      - "5432:5432"
    volumes:
      - productos_data:/var/lib/postgresql/data # Persistencia de datos-
    networks:
      - microservicios-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U productos_user -d productos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

# Servicios de microservicios
  productos:
    build:
      context: ./productos
    container_name: productos-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-productos:5432/productos_db
      SPRING_DATASOURCE_USERNAME: productos_user
      SPRING_DATASOURCE_PASSWORD: productos_pass
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      postgres-productos:
        condition: service_healthy
    networks:
      - microservicios-net
    restart: unless-stopped

volumes:
  productos_data:

networks:
  microservicios-net:
    driver: bridge