management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: productos-service
  datasource:
    url: jdbc:postgresql://postgres-productos:5432/productos_db
    username: productos_user
    password: productos_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Cambiar a 'validate' en producción o si se gestiona el esquema externamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Formatea el SQL en los logs para mejor legibilidad
# Configuración de OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha # Ordena las operaciones alfabéticamente
    tags-sorter: alpha # Ordena las etiquetas alfabéticamente
    try-it-out-enabled: true # Habilita el botón "Try it out"